name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Go to the App Directory
      run: cd ShoppiApp
    - name: Install bundle
      run: |
        bundle config path vendor/bundle
        bundle insall --jobs 4 --retry 3
    - name: Create Firebase Service Credentials file
      run: |
        cd ShoppiApp/FirebaseAppDistributionConfig
        echo "$FIREBASE_CREDENTIALS" > firebase_creadenfials.json.b64
        base64 -d -i firebase_creadenfials.json.b64 > firebase_credentials.json
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
    - name: Distribute app with 🔥 App Distribution 🚀
      run: bundle exec fastlane distribute
      env:
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
