name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install bundle
      run: |
        cd ShoppiApp
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Create Firebase Service Credentials file
      run: |
        cd ShoppiApp/FirebaseAppDistributionConfig
        echo "$FIREBASE_CREDENTIALS" > firebase_creadenfials.json.b64
        base64 -d -i firebase_creadenfials.json.b64 > firebase_credentials.json
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
    - name: Distribute app with 🔥 App Distribution 🚀
      run: |
        cd ShoppiApp
        bundle exec fastlane ios_distribute
      env:
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
